"""Shared desktop/server contracts for Sopotek Quant System.

This package is the source of truth for transport-safe DTOs, commands, events,
enums, envelopes, and runtime context models that must stay free of UI,
broker-SDK, and ORM dependencies.
"""

from contracts.base import (
    CommandEnvelope,
    ContractModel,
    CorrelationIds,
    EnvelopeHeaders,
    ErrorDetail,
    EventEnvelope,
    ProducerIdentity,
    ResponseEnvelope,
    RuntimeContext,
    utc_now,
)
from contracts.enums import (
    AlertSeverity,
    AssetClass,
    AuthMethod,
    DecisionAction,
    EnvironmentName,
    ExecutionStatus,
    HealthStatus,
    LearningOutcome,
    MarketStatus,
    MessageTopic,
    OrderType,
    ProducerRole,
    ReportKind,
    RiskDisposition,
    SessionMode,
    SessionRole,
    SessionState,
    TimeInForce,
    TradeSide,
    VenueKind,
)

__all__ = [
    "AlertSeverity",
    "AssetClass",
    "AuthMethod",
    "CommandEnvelope",
    "ContractModel",
    "CorrelationIds",
    "DecisionAction",
    "EnvironmentName",
    "EnvelopeHeaders",
    "ErrorDetail",
    "EventEnvelope",
    "ExecutionStatus",
    "HealthStatus",
    "LearningOutcome",
    "MarketStatus",
    "MessageTopic",
    "OrderType",
    "ProducerIdentity",
    "ProducerRole",
    "ReportKind",
    "ResponseEnvelope",
    "RiskDisposition",
    "RuntimeContext",
    "SessionMode",
    "SessionRole",
    "SessionState",
    "TimeInForce",
    "TradeSide",
    "VenueKind",
    "utc_now",
]
